# Generated by Django 4.0.4 on 2022-05-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_muallif_kitoblar_soni_alter_record_qaytarish_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bitiruvchi',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='record',
            name='sana',
            field=models.DateField(null=True),
        ),
    ]
