# Generated by Django 4.0.4 on 2022-05-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='speciality',
            field=models.ManyToManyField(null=True, to='university.speciality'),
        ),
    ]
