# Generated by Django 4.0.4 on 2022-05-17 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_subject_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='speciality',
        ),
        migrations.AddField(
            model_name='subject',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.speciality'),
        ),
    ]
